apiVersion: v1
kind: BuildConfig
metadata:
  name: cpat-team-one.node-express-og
  labels:
    app: node-express-og
spec:
  triggers:
    - type: GitHub
      github:
        secret: secret101
  source:
    git:
      uri: 'https://github.com/cpat-team-one/node-express-og.git'
      ref: master
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfilePath: Jenkinsfile
      env:
        - name: CLOUD_NAME
          value: openshift
        - name: NAMESPACE
          value: dev-og
        - name: BRANCH
          value: master
